# Generated by Django 3.0.6 on 2020-06-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="count",
            field=models.IntegerField(default=0, help_text="읽은 유저 수"),
        ),
        migrations.AddField(
            model_name="post",
            name="public",
            field=models.BooleanField(default=False, help_text="공개 여부"),
        ),
        migrations.AlterField(
            model_name="post",
            name="message",
            field=models.TextField(blank=True, help_text="메시지"),
        ),
    ]
